name: " 🔩 - Create/Delete Kube Namespace"

on:
  pull_request:
    types: [opened, reopened, closed]

env:
  AZ_RESOURCE_GROUP: "tgrall-demo"
  AZ_CLUSTER_NAME: "tug-kube"
  ACTION: "create"

jobs:

  kube_namespace:
    runs-on: ubuntu-latest
    
    steps:

      # control if the workflow should create or delete the kubernetes namespace
      # - created when PR is opened or reopened
      # - delete when PR is closed
      - name: Set env ACTION
        run: |
          if [[ $GITHUB_EVENT_NAME == 'closed' ]]; then
              echo "ACTION=delete" >> "$GITHUB_ENV"
          fi

      - name: Branch name
        run: "echo running on branch ${{github.head_ref}}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"    
  
      # login to azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        id: getContext
        run: |
          az aks get-credentials --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_CLUSTER_NAME }} --file $GITHUB_WORKSPACE/kubeconfig
          echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig" >> $GITHUB_ENV

      - name: Create namespace
        id: createNameSpace
        run: |
          kubectl ${{ env.ACTION }} namespace dev-pr-${{ github.head_ref }}
