name: 📦 Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]



jobs:
  
  build_and_publish:
    runs-on: tug-container
    permissions: 
      contents: read
      packages: write 
    steps:

      - uses: hmarr/debug-action@v2

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        env:
          MAVEN_USERNAME: octodemobot
          MAVEN_GHPR_PASSWORD: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
        run: |
          mvn -B package --file pom.xml -Dmaven.test.skip=true
          mkdir ANNADEMO

      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: octodemobo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        id: container_publish
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSION=1.0.0
            REPOSITORY_NAME=${{ github.repository }}
            revision=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

      
